# Generated by Django 3.2.5 on 2022-03-10 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnnouncedPuResults',
            fields=[
                ('result_id', models.IntegerField(primary_key=True, serialize=False)),
                ('polling_unit_uniqueid', models.CharField(max_length=50)),
                ('party_abbreviation', models.CharField(max_length=4)),
                ('party_score', models.IntegerField(max_length=11)),
                ('entered_by_user', models.CharField(max_length=50)),
                ('date_entered', models.DateField()),
                ('user_ip_address', models.CharField(max_length=50)),
            ],
        ),
    ]
